### ISSUE TITLE
QR Code Scanner View always pops up error "Could not register for push notifications"

### ISSUE THREAD

**Issue by chapmant** [LaunchKey/launchkey-android-whitelabel-sdk#1]
After following the LaunchKey instructions for setting up push notifications, I still get the error "Could not register for push notifications."

What information would be useful for helping to debug this?

**Comment by chapmant** [comment]
After playing around with it some more, it actually registers the device, and I can successfully authenticate using the AuthRequestsFragment.

**Comment by arjleon** [comment]
Hi, thanks for reporting the issue. We'll investigate on our end to figure why that keeps showing for you even when everything has been set in place for GCM to properly work like suggested in GCM's developer website.

And yes, if that GCM error is returned, that would be the only instance where the device is successfully linked even though it might not have full registered with the GCM service.

In the meantime, I would like to point out that error handling will be greatly improved across the White Label SDK and should be a huge thing of the upcoming **2.2.0** release.

**Comment by chapmant** [comment]
This was solved for me in the meeting this morning!

**Comment by arjleon** [comment]
It seems like this issue (#1) and #2 are related to the same problem when in the process of setting GCM up for push notifications.

For whoever comes across the same issue: The Google Play Services plugin in the app-level build.gradle needs to be present at the top as `apply plugin: 'com.google.gms.google-services'` right after `apply plugin: 'com.android.application'`. And for the plugin to properly work, the dependency has to be present in the project-level build.gradle file as `classpath 'com.google.gms:google-services:1.5.0'` right after `classpath 'com.android.tools.build:gradle:2.1.2'` in the `buildscript` > `dependencies` brackets.

Pointing out once more how the upcoming 2.2 and later releases will improve error handling, including problems with GCM, that should make things better for implementers.
