### ISSUE TITLE
Auth request with security factor requirements does not allow authentication after adding factors from request screen

### ISSUE THREAD

**Issue by nvoigt** [LaunchKey/launchkey-android-whitelabel-sdk#10]
I'm running into a bug where the user cannot approve an authentication request if they have not previously set up a security factor and then attempt to set one up. This is using version 2.2.1 of the whitelabel sdk. I can repeat it using the following steps:

1. Successfully register/link the device
2. Do not set up any security factors
3. Send an auth request to the device
4. The Whitelabel fragment will pop up indicating that the user cannot authorize the request until they set up a security factor.
5. Tap on the link "tap here". This takes you to a screen to set up a factor.
6. Set up a pin code and hit the checkmark

This returns you to the request screen that does not acknowledge you have set up any factors. Hitting the "tap here" link again and going back does not update the request screen. Setting more than one security factor does not update the request screen.

**Comment by arjleon** [comment]
Thanks for the feedback, we'll make sure we tackle this as well. I'll keep this issue up to date.

**Comment by arjleon** [comment]
This has been fixed as of v2.3.0, released today. It will now automatically refresh of there has been a change in the factors set.
