### ISSUE TITLE
Crash on registration with 2.2.1 SDK

### ISSUE THREAD

**Issue by chapmant** [LaunchKey/launchkey-android-whitelabel-sdk#11]
> 

         AndroidRuntime  E  FATAL EXCEPTION: AsyncTask #3
                         E  Process: com.iovation.mobile.android.myapplication, PID: 12285
                         E  java.lang.RuntimeException: An error occurred while executing doInBackground()
                         E      at android.os.AsyncTask$3.done(AsyncTask.java:309)
                         E      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                         E      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                         E      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                         E      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                         E      at java.lang.Thread.run(Thread.java:818)
                         E  Caused by: java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.android.gms.iid.zzd'
                            appears in /data/app/com.iovation.mobile.android.myapplication-1/base.apk)
                         E      at com.google.android.gms.iid.zzd.zzdL(Unknown Source)
                         E      at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                         E      at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                         E      at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                         E      at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                         E      at com.launchkey.android.whitelabel.sdk.gcm.GcmInternalRegistrar.doInBackground(Unknown Source)
                         E      at com.launchkey.android.whitelabel.sdk.gcm.GcmInternalRegistrar.doInBackground(Unknown Source)
                         E      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                         E      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                         E      ... 4 more

This crash reliably comes up every time I try to register a device using the 2.2.1 SDK, preventing registration of devices.

**Comment by arjleon** [comment]
I've seen that happening usually when the SDK and the client differ on the version for Google Play Services, specially the GCM dependency. Do you mind showing me the list of dependencies in your app-level gradle.build file?

**Comment by chapmant** [comment]
>    compile 'com.android.support:support-v4:24.2.0'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.android.support:design:24.2.0'
    compile 'com.android.support:cardview-v7:24.2.0'
    compile 'com.google.android.gms:play-services-base:8.3.0'
    compile 'com.google.android.gms:play-services-location:8.3.0'
    compile 'com.google.android.gms:play-services-maps:8.3.0'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
    compile 'com.google.android.gms:play-services-vision:8.3.0'

There's all our google and android dependencies that we've got right now. Using 8.3.0, as per your documentation.

**Comment by chapmant** [comment]
So it appears it might be an issue with API level 24, lowered it to target/compile against 23, with the 23 support libs, and the crash stopped.

**Comment by arjleon** [comment]
Yeah, I was about to suggest sticking to 23 until the SDK is fully compatible with API 24.

**Comment by arjleon** [comment]
Closing issue: Compile against API 23 until it's API 24-compatible. I've created a separate issue (#14) to keep track of that enhancement request.
