### ISSUE TITLE
When using the .registerUser() function, response is always "method POST must have a request body."

### ISSUE THREAD

**Issue by chapmant** [LaunchKey/launchkey-android-whitelabel-sdk#2]
When I set up the callback functions for the .registerUser() function for my own UI for typing in a code, the response I get back is always onFailure() with an error code of 1000, and an error message of "method POST must have a request body".

```
07-19 12:03:55.638 18759-18759/com.iovation.mobile.android.myapplication D/EDITTEXT: button pressed
07-19 12:03:55.638 18759-18759/com.iovation.mobile.android.myapplication D/REGISTER: attempting to register
07-19 12:03:55.658 18759-18759/com.iovation.mobile.android.myapplication D/REGISTER: attempt sent
07-19 12:03:56.434 18759-18759/com.iovation.mobile.android.myapplication D/CALLBACK: started (onStarted)
07-19 12:04:38.481 18759-18759/com.iovation.mobile.android.myapplication D/CALLBACK: verifying code (onVerifyingCode)
07-19 12:04:38.829 18759-18759/com.iovation.mobile.android.myapplication D/CALLBACK: 1000 (onFailure)
07-19 12:04:38.830 18759-18759/com.iovation.mobile.android.myapplication D/CALLBACK: method POST must have a request body. (onFailure)
07-19 12:04:38.831 18759-18759/com.iovation.mobile.android.myapplication D/CALLBACK: false (isDeviceLinked)
```

**Comment by arjleon** [comment]
Thanks for submitting the issue. We're looking into it as we try to recreate it and keep this up to date.

It seems to be happening when implementing a fully custom user interface and then making use of the `registerUser(...)` method. May I ask if you've tried the default user interface by calling `displayLinkingUi(...)` to see if the issue still persists?

Thanks!

**Comment by chapmant** [comment]
When I use the `.displayLinkingUi()` call, I get the "Could not register for push notifications," pop-up, but nothing about the POST request body.

Additionally, when I use `.displayLinkingUi()`, the call to `.isDeviceLinked()` returns true after the POST error, but when I use `.registerUser()`, passing in a valid code, `.isDeviceLinked()` returns false.

**Comment by arjleon** [comment]
Ok so this seems to limit the scope of the issue you're hitting to just the call of `.registerUser(...)`.
Thanks a lot for checking that out. I'll look into it again know that now and I'll keep this issue up to date.

**Comment by arjleon** [comment]
It seems like this issue (#2) and #1 are related to the same problem when in the process of setting GCM up for push notifications.

For whoever comes across the same issue: The Google Play Services plugin in the app-level build.gradle needs to be present at the top as `apply plugin: 'com.google.gms.google-services'` right after `apply plugin: 'com.android.application'`. And for the plugin to properly work, the dependency has to be present in the project-level build.gradle file as `classpath 'com.google.gms:google-services:1.5.0'` right after `classpath 'com.android.tools.build:gradle:2.1.2'` in the `buildscript` > `dependencies` brackets.

Pointing out once more how the upcoming 2.2 and later releases will improve error handling, including problems with GCM, that should make things better for implementers.
