### ISSUE TITLE
.registerUser() gives "Could not register for push notifications" error when .displayLinkingUi() successfully registers

### ISSUE THREAD

**Issue by chapmant** [LaunchKey/launchkey-android-whitelabel-sdk#3]
When I try to register with a code through the `.registerUser(...)` function, it returns an error of "Could not register for push notifications" but successfully registers the device for authentication.

If I swap out the code for LaunchKey's fragment, it successfully registers for authentication as well as push notifications.

`07-21 09:10:00.329 19971-19971/com.iovation.mobile.android.myapplication D/EDITTEXT: button pressed

07-21 09:10:00.330 19971-19971/com.iovation.mobile.android.myapplication D/REGISTER: attempting to register

07-21 09:10:00.349 19971-19971/com.iovation.mobile.android.myapplication D/REGISTER: attempt sent

07-21 09:11:58.068 19971-19971/com.iovation.mobile.android.myapplication D/EDITTEXT: button pressed

07-21 09:11:58.070 19971-19971/com.iovation.mobile.android.myapplication D/REGISTER: attempting to register

07-21 09:11:58.078 19971-19971/com.iovation.mobile.android.myapplication D/REGISTER: attempt sent

07-21 09:11:58.876 19971-19971/com.iovation.mobile.android.myapplication D/CALLBACK: verifying code (onVerifyingCode)

07-21 09:12:00.362 19971-19971/com.iovation.mobile.android.myapplication D/CALLBACK: 1000 (onFailure)

07-21 09:12:00.362 19971-19971/com.iovation.mobile.android.myapplication D/CALLBACK: Could not register for push notifications (onFailure)

07-21 09:12:00.364 19971-19971/com.iovation.mobile.android.myapplication D/CALLBACK: true (isDeviceLinked)`

**Comment by aenglander** [comment]
You issue has been assigned and is being triaged. We'll be updating the issue today with information or requests for additional information.

**Comment by arjleon** [comment]
I'm sorry you're running into this issue now. Could you tell which method you're calling? The one allowing for a custom device name? Our default interface hooks into that very same method so I'm wondering why that would make a different. Thanks in advance.

**Comment by chapmant** [comment]
The one that I've been calling is `WhiteLabelManager.registerUser(Context context, String code, UserRegistrationListener listener)`. I'll try it with the custom device name one at some point today and see if that fixes anything for me.

**Comment by arjleon** [comment]
If this issue is something that was definitely fixed with the latest 2.2 release, I'll close it down in the near future.

**Comment by arjleon** [comment]
Solved in the latest 2.2 release. Re-open if necessary.
