### ISSUE TITLE
Deprecate checkActiveStatus

### ISSUE THREAD

**Issue by aenglander** [LaunchKey/launchkey-android-whitelabel-sdk#5]
There is no proper way to fix this call. It gives the implementer a false sense of confidence that the value is correct. The only way to know if there are active sessions is via a status call or an authorizations list refresh. There currently is a event driven option with the ```onSessionUpdate``` method of the ```SessionListener```. As such, this call needs to be deprecated in a future release.

**Comment by arjleon** [comment]
Enhancement has been pushed to the repo. It will be part of the next release.
