### ISSUE TITLE
Null Pointer Exception when doing a FragmentTransaction away from AuthRequestFragment after app is backgrounded, then launched from a notification

### ISSUE THREAD

**Issue by chapmant** [LaunchKey/launchkey-android-whitelabel-sdk#6]
> 

                         E  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v4.app.FragmentA
                            ctivity.isFinishing()' on a null object reference
                         E      at com.launchkey.android.whitelabel.sdk.ui.RequestFragment.s(Unknown Source)
                         E      at com.launchkey.android.whitelabel.sdk.ui.RequestFragment.j(Unknown Source)
                         E      at com.launchkey.android.whitelabel.sdk.ui.cs.onRequestHandled(Unknown Source)
                         E      at com.launchkey.android.whitelabel.sdk.auth.e.handleMessage(Unknown Source)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5422)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                Process  I  Sending signal. PID: 3114 SIG: 9`

My application consuming the white label SDK throws a notification when there is a new auth request, then once actioned on, launches the app, and then does a fragment transaction away from the home screen to the AuthRequestFragment, and then once the auth request is approved or denied, does another fragment transaction in the onSuccess callback to switch back to the home screen view. In most situations, the home > auth > home transactions work perfectly, but when it's being done due to a push notification, the LaunchKey SDK throws a null pointer exception.

**Comment by arjleon** [comment]
Thanks for reporting the issue! We'll look into it and keep the issue up to date.

**Comment by arjleon** [comment]
Quick question, you are referring to the "AccountStateListener#onAuthenticationSuccess(...)" callback? Also, have you realized if it happened when the alert dialog popping up in the AuthRequestFragment displaying a new request has been received invalidating the previous one? Thanks in advance!

**Comment by chapmant** [comment]
Yes, it's the `AccountStateListener#onAuthenticationSuccess(...)` callback.

I do not believe that is what is happening, as I'm logging in to a non-shared account, and it happens every time that I try to log in from a notification.

The main difference that I've noticed in the activity lifecycle is that when I tap on the notification to get into the application, it calls the `onDestroy()` function for the application and activity. This does not get called when I background the activity and then bring it to the foreground through multitasking, and when I check for any requests then, it does not crash.

Is there any chance, since you mention that possibility, that there's an old request hanging around that isn't getting actioned on by the crashes?

**Comment by arjleon** [comment]
I don't believe it has something to do with a potentially-pending Auth Request. It might have something to do with the fact that the Activity is destroyed by the time that call is made. Therefore, the NullPointerException on the `getActivity()` call is thrown if the reference to the activity returns `null`. We'll make sure an extra check is made. In the meantime, I'll continue attempting to recreate the issue now that I have some extra information on the lifecycle of the Activity hosting AuthRequestFragment.

Thanks for the input! I'll keep this issue updated.

**Comment by arjleon** [comment]
Closing issue; the fix is part of the latest v2.2.1 release.
