### ISSUE TITLE
Slow Android Registration Timing

### ISSUE THREAD

**Issue by nvoigt** [LaunchKey/launchkey-android-whitelabel-sdk#7]
I’ve been testing the user registration portion of our Android app and I’m running into some issues with timings around the UserRegistrationListener. I did timed the callback from when onStarted() is called until onSuccess() is called. Last Thursday I tested this 5 times on a Samsung Galaxy S6 running 6.0.1 and every run took 25 seconds to complete. Today I tested on a Moto E running 5.1 and saw timings from 4 seconds to 23 seconds. I also retested on the Galaxy S6 today and saw timings from 10 seconds to 36 seconds. For comparison the equivalent iOS call is taking less than 1.5 seconds consistently. The Android registration timing should be identical to the iOS registration timing.

All of these test runs are against the AWS instance. Considering the iOS timings this seems to be an Android specific issue.

**Comment by arjleon** [comment]
I would like to point out that the greatest majority of the time its due to the generation of a large RSA key pair. Sadly it is not as fast as it is done natively on iOS, plus the size of the key is fairly big, so it comes down to how fast the CPU can generate it. The actual linking network call is fairly fast so we'll still check it out to make sure that happens as fast as a device allows and we'll keep this ticket up to date on our findings.

**Comment by nvoigt** [comment]
Any update on this? We're still seeing this slow down even pointed at the on-prem solution. If there are no performance gains that can be made is it possible to break out the RSA key pairing or move it so that it can be computed in advance of the registration call? Having the user wait this long for registration to complete is not acceptable for our application.

**Comment by degan** [comment]
It is on the hardware side of things, the endpoint it is hitting will never speed this process up. Creating key pairs can take a long time on Android, I believe they are currently 4096. We could speed the process up by allowing you to create smaller keys (2048 is typically considered safe) and we could look at ways of optimizing the UX so it starts generating earlier, etc. Armando is out until Wednesday,  so we will review when he returns.

**Comment by arjleon** [comment]
The RSA keys are 4096. We have discussed a few things we can try to speed things up. We are looking into it and we'll keep this Issue up to date with what we find that helps RSA keys stay at a size considered safe.

**Comment by arjleon** [comment]
This has been tackled and improved as of v2.3.0, released today. `WhiteLabelManager` will now start generating the key pair as soon as it's initialized, usually finalizing its generation by the time the user attempts to link the device. The `WhiteLabelConfig` object passed to `WhiteLabelManager.init(WhiteLabelConfig)` can now specify the size of the key pair between 2048 (min) and 4096 (max/default) by calling `WhiteLabelConfig.Builder.keyPairSize(int)`.
